// Code generated by go-swagger; DO NOT EDIT.

// Package restapi Swagger Petstore
//
//  This is a sample server Petstore server.  You can find out more about     Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).      For this sample, you can use the api key `special-key` to test the authorization     filters.
//  Terms Of Service:
//    http://swagger.io/terms/
//  Schemes:
//    http
//  Host: 127.0.0.1:9999
//  BasePath: /v2
//  Version: 1.0.0
//  License: Apache 2.0 http://www.apache.org/licenses/LICENSE-2.0.html
//  Contact: <apiteam@swagger.io>
//
//  Consumes:
//    - application/json
//
//  Produces:
//    - application/json
//
// swagger:meta
package restapi
