// Code generated by go-swagger; DO NOT EDIT.

package pet

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetPetByIDHandlerFunc turns a function with the right signature into a get pet by Id handler
type GetPetByIDHandlerFunc func(GetPetByIDParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetPetByIDHandlerFunc) Handle(params GetPetByIDParams) middleware.Responder {
	return fn(params)
}

// GetPetByIDHandler interface for that can handle valid get pet by Id params
type GetPetByIDHandler interface {
	Handle(GetPetByIDParams) middleware.Responder
}

// NewGetPetByID creates a new http.Handler for the get pet by Id operation
func NewGetPetByID(ctx *middleware.Context, handler GetPetByIDHandler) *GetPetByID {
	return &GetPetByID{Context: ctx, Handler: handler}
}

/*GetPetByID swagger:route GET /pet/{petId} pet getPetById

Find pet by ID

Returns a single pet

*/
type GetPetByID struct {
	Context *middleware.Context
	Handler GetPetByIDHandler
}

func (o *GetPetByID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetPetByIDParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
