// Code generated by go-swagger; DO NOT EDIT.

package pet

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/CyrusJavan/terraform-provider-example/models"
)

// AddPetReader is a Reader for the AddPet structure.
type AddPetReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *AddPetReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewAddPetOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 405:
		result := NewAddPetMethodNotAllowed()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewAddPetOK creates a AddPetOK with default headers values
func NewAddPetOK() *AddPetOK {
	return &AddPetOK{}
}

/*AddPetOK handles this case with default header values.

successfully added
*/
type AddPetOK struct {
	Payload *models.Pet
}

func (o *AddPetOK) Error() string {
	return fmt.Sprintf("[POST /pet][%d] addPetOK  %+v", 200, o.Payload)
}

func (o *AddPetOK) GetPayload() *models.Pet {
	return o.Payload
}

func (o *AddPetOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Pet)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewAddPetMethodNotAllowed creates a AddPetMethodNotAllowed with default headers values
func NewAddPetMethodNotAllowed() *AddPetMethodNotAllowed {
	return &AddPetMethodNotAllowed{}
}

/*AddPetMethodNotAllowed handles this case with default header values.

Invalid input
*/
type AddPetMethodNotAllowed struct {
}

func (o *AddPetMethodNotAllowed) Error() string {
	return fmt.Sprintf("[POST /pet][%d] addPetMethodNotAllowed ", 405)
}

func (o *AddPetMethodNotAllowed) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
