// Code generated by go-swagger; DO NOT EDIT.

package pet

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/CyrusJavan/terraform-provider-example/models"
)

// NewUpdatePetParams creates a new UpdatePetParams object
// with the default values initialized.
func NewUpdatePetParams() *UpdatePetParams {
	var ()
	return &UpdatePetParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewUpdatePetParamsWithTimeout creates a new UpdatePetParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewUpdatePetParamsWithTimeout(timeout time.Duration) *UpdatePetParams {
	var ()
	return &UpdatePetParams{

		timeout: timeout,
	}
}

// NewUpdatePetParamsWithContext creates a new UpdatePetParams object
// with the default values initialized, and the ability to set a context for a request
func NewUpdatePetParamsWithContext(ctx context.Context) *UpdatePetParams {
	var ()
	return &UpdatePetParams{

		Context: ctx,
	}
}

// NewUpdatePetParamsWithHTTPClient creates a new UpdatePetParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewUpdatePetParamsWithHTTPClient(client *http.Client) *UpdatePetParams {
	var ()
	return &UpdatePetParams{
		HTTPClient: client,
	}
}

/*UpdatePetParams contains all the parameters to send to the API endpoint
for the update pet operation typically these are written to a http.Request
*/
type UpdatePetParams struct {

	/*Body
	  Pet object that needs to be added to the store

	*/
	Body *models.Pet

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the update pet params
func (o *UpdatePetParams) WithTimeout(timeout time.Duration) *UpdatePetParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update pet params
func (o *UpdatePetParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update pet params
func (o *UpdatePetParams) WithContext(ctx context.Context) *UpdatePetParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update pet params
func (o *UpdatePetParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update pet params
func (o *UpdatePetParams) WithHTTPClient(client *http.Client) *UpdatePetParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update pet params
func (o *UpdatePetParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the update pet params
func (o *UpdatePetParams) WithBody(body *models.Pet) *UpdatePetParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the update pet params
func (o *UpdatePetParams) SetBody(body *models.Pet) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *UpdatePetParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
