// Code generated by go-swagger; DO NOT EDIT.

package pet

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewDeletePetParams creates a new DeletePetParams object
// with the default values initialized.
func NewDeletePetParams() *DeletePetParams {
	var ()
	return &DeletePetParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeletePetParamsWithTimeout creates a new DeletePetParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeletePetParamsWithTimeout(timeout time.Duration) *DeletePetParams {
	var ()
	return &DeletePetParams{

		timeout: timeout,
	}
}

// NewDeletePetParamsWithContext creates a new DeletePetParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeletePetParamsWithContext(ctx context.Context) *DeletePetParams {
	var ()
	return &DeletePetParams{

		Context: ctx,
	}
}

// NewDeletePetParamsWithHTTPClient creates a new DeletePetParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeletePetParamsWithHTTPClient(client *http.Client) *DeletePetParams {
	var ()
	return &DeletePetParams{
		HTTPClient: client,
	}
}

/*DeletePetParams contains all the parameters to send to the API endpoint
for the delete pet operation typically these are written to a http.Request
*/
type DeletePetParams struct {

	/*PetID
	  Pet id to delete

	*/
	PetID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete pet params
func (o *DeletePetParams) WithTimeout(timeout time.Duration) *DeletePetParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete pet params
func (o *DeletePetParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete pet params
func (o *DeletePetParams) WithContext(ctx context.Context) *DeletePetParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete pet params
func (o *DeletePetParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete pet params
func (o *DeletePetParams) WithHTTPClient(client *http.Client) *DeletePetParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete pet params
func (o *DeletePetParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithPetID adds the petID to the delete pet params
func (o *DeletePetParams) WithPetID(petID int64) *DeletePetParams {
	o.SetPetID(petID)
	return o
}

// SetPetID adds the petId to the delete pet params
func (o *DeletePetParams) SetPetID(petID int64) {
	o.PetID = petID
}

// WriteToRequest writes these params to a swagger request
func (o *DeletePetParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param petId
	if err := r.SetPathParam("petId", swag.FormatInt64(o.PetID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
